---
Name: ideannotator
Before:
  - 'mysite/*'
After:
  - 'framework/*'
  - 'cms/*'
---
DataObject:
  extensions:
    - Annotatable
AnnotatePermissionChecker:
  enabled: false
  enabled_modules:
    - mysite
